language: bash

node_js:
    - "9.5"

install:
    - npm install

script:
    - node index.js

deploy:
    - provider: pages
      skip-cleanup: true
      local-dir: platforms
      github-token: $GITHUB_TOKEN
      verbose: true
      on:
        branch: master

after_deploy:
    - /bin/bash push.sh